# health check
GET http://localhost:8085/lra-coordinator/health
###
# create LRA instance
POST http://localhost:8085/lra-coordinator/instance
Content-Type: application/json

{
  "retryLimit" : "5"
}
###
# cancel LRA instance
POST http://localhost:8085/lra-coordinator/instance/cancel
Content-Type: application/json

{
  "uuid" : "this-is-sample-uuid"
}
###
# register a get eureka applicant
POST http://localhost:8085/lra-coordinator/eurekaapplicant
Content-Type: application/json

{
  "lraInstanceEntityUUID": "this-is-sample-uuid",
  "appName": "state-machine",
  "serviceName": "state-machine-health-v1",
  "httpMethod": "GET",
  "pathVariables": "123/456/789",
  "requestParameters": {
    "param1": "value1"
  },
  "requestBodyInJSON": "{ \"factoryName\" : \"type1\" }",
  "connectTimeout": 20000,
  "readTimeout": 20000
}
###
# register a post eureka applicant
POST http://localhost:8085/lra-coordinator/eurekaapplicant
Content-Type: application/json

{
  "lraInstanceEntityUUID": "this-is-sample-uuid",
  "appName": "state-machine",
  "serviceName": "state-machine-create-v1",
  "httpMethod": "POST",
  "pathVariables": null,
  "requestParameters": null,
  "requestBodyInJSON": "{ \"factoryName\" : \"type1\" }"
}